def u(id, w=700):
    return f"https://images.unsplash.com/{id}?auto=format&fit=crop&w={w}&q=72"

RESTAURANTS = [
    {"id": "r1", "name": "Spice Symphony", "cuisine": "North Indian, Mughlai", "description": "Rich gravies and tandoor classics.", "address": "Connaught Place, New Delhi", "phone": "+91 98100 11001", "image": u("photo-1517248135467-4c7edcad34c4"), "rating": 4.5, "delivery_time": "25-30 min", "delivery_fee": 29, "is_active": 1},
    {"id": "r2", "name": "Dosa Junction", "cuisine": "South Indian", "description": "Crispy dosas & filter coffee.", "address": "T. Nagar, Chennai", "phone": "+91 98100 11002", "image": u("photo-1552566626-52f8b828add9"), "rating": 4.6, "delivery_time": "20-25 min", "delivery_fee": 19, "is_active": 1},
    {"id": "r3", "name": "Biryani Blues", "cuisine": "Biryani, Mughlai", "description": "Authentic Hyderabadi dum biryani.", "address": "Jubilee Hills, Hyderabad", "phone": "+91 98100 11003", "image": u("photo-1414235077428-338989a2e8c0"), "rating": 4.8, "delivery_time": "30-35 min", "delivery_fee": 0, "is_active": 1},
    {"id": "r4", "name": "Pizza Roma", "cuisine": "Italian, Pizza", "description": "Wood-fired artisan pizzas.", "address": "Koramangala, Bengaluru", "phone": "+91 98100 11004", "image": u("photo-1555396273-367ea4eb4db5"), "rating": 4.4, "delivery_time": "25-30 min", "delivery_fee": 25, "is_active": 1},
    {"id": "r5", "name": "Tokyo Bites", "cuisine": "Japanese, Asian", "description": "Sushi, ramen & bowls.", "address": "Indiranagar, Bengaluru", "phone": "+91 98100 11005", "image": u("photo-1554118811-1e0d58224f24"), "rating": 4.7, "delivery_time": "30-40 min", "delivery_fee": 49, "is_active": 1},
    {"id": "r6", "name": "Burger Barn", "cuisine": "Fast Food, American", "description": "Smashed burgers & loaded fries.", "address": "Bandra West, Mumbai", "phone": "+91 98100 11006", "image": u("photo-1466978913421-dad2ebd01d17"), "rating": 4.3, "delivery_time": "15-20 min", "delivery_fee": 15, "is_active": 1},
    {"id": "r7", "name": "Coastal Catch", "cuisine": "Seafood, Goan", "description": "Fresh catch cooked the Goan way.", "address": "Panjim, Goa", "phone": "+91 98100 11007", "image": u("photo-1559329007-40df8a9345d8"), "rating": 4.6, "delivery_time": "30-35 min", "delivery_fee": 35, "is_active": 1},
    {"id": "r8", "name": "Sweet Treats", "cuisine": "Desserts, Bengali Sweets", "description": "Melt-in-mouth sweets & desserts.", "address": "Park Street, Kolkata", "phone": "+91 98100 11008", "image": u("photo-1517248135467-4c7edcad34c4"), "rating": 4.5, "delivery_time": "20-25 min", "delivery_fee": 20, "is_active": 1},
    {"id": "r9", "name": "Kolkata Biryani House", "cuisine": "Biryani, Bengali", "description": "Legendary Kolkata-style biryani.", "address": "Alipore, Kolkata", "phone": "+91 98100 11009", "image": u("photo-1590846406792-0adc7f938f1d"), "rating": 4.7, "delivery_time": "35-40 min", "delivery_fee": 25, "is_active": 1},
    {"id": "r10", "name": "Dragon Wok", "cuisine": "Chinese, Asian", "description": "Street-style Indo-Chinese.", "address": "Sector 18, Noida", "phone": "+91 98100 11010", "image": u("photo-1537047902294-62a40c20a6ae"), "rating": 4.2, "delivery_time": "25-30 min", "delivery_fee": 20, "is_active": 1},
    {"id": "r11", "name": "Kebab Factory", "cuisine": "Kebab, Mughlai", "description": "Charcoal-grilled kebabs since 1987.", "address": "Hazratganj, Lucknow", "phone": "+91 98100 11011", "image": u("photo-1583394838336-acd977736f90"), "rating": 4.6, "delivery_time": "30-35 min", "delivery_fee": 30, "is_active": 1},
    {"id": "r12", "name": "Choco Loco", "cuisine": "Chocolate, Desserts", "description": "Handcrafted chocolate heaven.", "address": "Lower Parel, Mumbai", "phone": "+91 98100 11012", "image": u("photo-1600093463592-8e36ae95ef56"), "rating": 4.4, "delivery_time": "20-25 min", "delivery_fee": 25, "is_active": 1},
    {"id": "r13", "name": "The Spanish Fork", "cuisine": "Spanish, European", "description": "Paellas, tapas & sangria.", "address": "Cyber City, Gurugram", "phone": "+91 98100 11013", "image": u("photo-1560624052-449f5ddf0c31"), "rating": 4.3, "delivery_time": "35-45 min", "delivery_fee": 40, "is_active": 0},
    {"id": "r14", "name": "Donut Delight", "cuisine": "Donuts, Bakery", "description": "Freshly glazed, every morning.", "address": "Banjara Hills, Hyderabad", "phone": "+91 98100 11014", "image": u("photo-1607627289024-67271e24cbb8"), "rating": 4.5, "delivery_time": "15-20 min", "delivery_fee": 15, "is_active": 1},
    {"id": "r15", "name": "Punjab Grill", "cuisine": "North Indian, Punjabi", "description": "Bold flavours of Punjab.", "address": "Golden Temple Rd, Amritsar", "phone": "+91 98100 11015", "image": u("photo-1590846406792-0adc7f938f1d"), "rating": 4.4, "delivery_time": "25-30 min", "delivery_fee": 22, "is_active": 1},
    {"id": "r16", "name": "Roll Revolution", "cuisine": "Fast Food, Street Food", "description": "Kathi rolls, wraps & bowls.", "address": "FC Road, Pune", "phone": "+91 98100 11016", "image": u("photo-1466978913421-dad2ebd01d17"), "rating": 4.1, "delivery_time": "15-20 min", "delivery_fee": 10, "is_active": 1},
    {"id": "r17", "name": "Madras Meals", "cuisine": "South Indian", "description": "Home-style thalis & tiffin.", "address": "Besant Nagar, Chennai", "phone": "+91 98100 11017", "image": u("photo-1552566626-52f8b828add9"), "rating": 4.4, "delivery_time": "20-25 min", "delivery_fee": 15, "is_active": 1},
    {"id": "r18", "name": "Oven Stories", "cuisine": "Bakery, Desserts, Pizza", "description": "Bakes, cakes & sourdough pizzas.", "address": "Hauz Khas, New Delhi", "phone": "+91 98100 11018", "image": u("photo-1555396273-367ea4eb4db5"), "rating": 4.2, "delivery_time": "25-30 min", "delivery_fee": 20, "is_active": 1}
]

FOODS = [
    {"id": "f1", "restaurant_id": "r4", "cat": "Italian", "name": "Margherita Pizza", "description": "Classic pizza with mozzarella, fresh tomato & basil on a hand-tossed base.", "image": u("photo-1565299624946-b28f40a0ae38"), "price": 299, "discount_price": 249, "food_type": "VEG", "rating": 4.5, "preparation_time": "25 min", "is_available": 1, "ingredients": ["wheat flour", "mozzarella cheese", "tomato", "basil", "olive oil"]},
    {"id": "f2", "restaurant_id": "r4", "cat": "Italian", "name": "Farmhouse Supreme Pizza", "description": "Loaded with capsicum, onion, corn, mushroom & extra mozzarella cheese.", "image": u("photo-1513104890138-7c749659a591"), "price": 429, "discount_price": 349, "food_type": "VEG", "rating": 4.3, "preparation_time": "30 min", "is_available": 1, "ingredients": ["wheat flour", "cheese", "capsicum", "onion", "corn", "mushroom"]},
    {"id": "f3", "restaurant_id": "r4", "cat": "Italian", "name": "Chicken Tikka Pizza", "description": "Smoky chicken tikka chunks with onion & tikka drizzle.", "image": u("photo-1574071318508-1cdbab80d002"), "price": 469, "discount_price": 399, "food_type": "NON_VEG", "rating": 4.6, "preparation_time": "30 min", "is_available": 1, "ingredients": ["wheat flour", "chicken", "cheese", "onion", "tikka sauce"]},
    {"id": "f4", "restaurant_id": "r2", "cat": "South Indian", "name": "Masala Dosa", "description": "Golden crispy dosa with spiced potato filling, served with sambar & chutneys.", "image": u("photo-1668236543090-82eba5ee5976"), "price": 149, "discount_price": 119, "food_type": "VEG", "rating": 4.7, "preparation_time": "15 min", "is_available": 1, "ingredients": ["rice", "urad dal", "potato", "onion", "spices"]},
    {"id": "f5", "restaurant_id": "r2", "cat": "South Indian", "name": "Idli Sambar (4 pcs)", "description": "Soft steamed idlis dunked in piping hot sambar.", "image": u("photo-1589301760014-d929f3979dbc"), "price": 119, "discount_price": 99, "food_type": "VEG", "rating": 4.4, "preparation_time": "15 min", "is_available": 1, "ingredients": ["rice", "urad dal", "vegetables", "tamarind"]},
    {"id": "f6", "restaurant_id": "r2", "cat": "Drinks", "name": "Filter Coffee", "description": "Strong South Indian filter coffee with frothy milk.", "image": u("photo-1495474472287-4d71bcdd2085"), "price": 79, "discount_price": None, "food_type": "VEG", "rating": 4.6, "preparation_time": "10 min", "is_available": 1, "ingredients": ["coffee", "milk", "sugar"]},
    {"id": "f7", "restaurant_id": "r1", "cat": "North Indian", "name": "Paneer Butter Masala", "description": "Cottage cheese simmered in silky tomato-cashew gravy.", "image": u("photo-1631452180519-c014fe946bc7"), "price": 289, "discount_price": 239, "food_type": "VEG", "rating": 4.6, "preparation_time": "25 min", "is_available": 1, "ingredients": ["paneer", "butter", "cream", "tomato", "cashew paste"]},
    {"id": "f8", "restaurant_id": "r1", "cat": "North Indian", "name": "Butter Chicken", "description": "Tandoori chicken in rich buttery tomato gravy.", "image": u("photo-1565557623262-b51c2513a641"), "price": 349, "discount_price": 299, "food_type": "NON_VEG", "rating": 4.7, "preparation_time": "30 min", "is_available": 1, "ingredients": ["chicken", "butter", "cream", "tomato", "cashew paste"]},
    {"id": "f9", "restaurant_id": "r1", "cat": "North Indian", "name": "Dal Makhani", "description": "Slow-cooked black lentils finished with butter & cream.", "image": u("photo-1547592180-85f173990554"), "price": 229, "discount_price": 199, "food_type": "VEG", "rating": 4.4, "preparation_time": "30 min", "is_available": 1, "ingredients": ["black lentils", "butter", "cream", "tomato"]},
    {"id": "f10", "restaurant_id": "r1", "cat": "Breads", "name": "Butter Naan (2 pcs)", "description": "Soft tandoor naans brushed with butter.", "image": u("photo-1585937421612-70a008356fbe"), "price": 59, "discount_price": 49, "food_type": "VEG", "rating": 4.5, "preparation_time": "15 min", "is_available": 1, "ingredients": ["wheat flour", "milk", "butter", "yeast"]},
    {"id": "f11", "restaurant_id": "r3", "cat": "Biryani", "name": "Hyderabadi Chicken Biryani", "description": "Fragrant dum biryani with saffron, mint & fried onion.", "image": u("photo-1563379091339-03b21ab4a4f8"), "price": 329, "discount_price": 279, "food_type": "NON_VEG", "rating": 4.8, "preparation_time": "35 min", "is_available": 1, "ingredients": ["basmati rice", "chicken", "yogurt", "saffron", "cashew", "onion"]},
    {"id": "f12", "restaurant_id": "r3", "cat": "Biryani", "name": "Veg Dum Biryani", "description": "Garden vegetables layered with aromatic basmati rice.", "image": u("photo-1589302168068-964664d93dc0"), "price": 259, "discount_price": 219, "food_type": "VEG", "rating": 4.3, "preparation_time": "30 min", "is_available": 1, "ingredients": ["basmati rice", "vegetables", "yogurt", "cashew", "saffron"]},
    {"id": "f13", "restaurant_id": "r9", "cat": "Biryani", "name": "Kolkata Mutton Biryani", "description": "Signature Kolkata biryani with potato & boiled egg.", "image": u("photo-1596797038530-2c107229654b"), "price": 399, "discount_price": 349, "food_type": "NON_VEG", "rating": 4.7, "preparation_time": "40 min", "is_available": 1, "ingredients": ["basmati rice", "mutton", "potato", "yogurt", "boiled egg"]},
    {"id": "f14", "restaurant_id": "r5", "cat": "Japanese", "name": "Sushi Platter (8 pcs)", "description": "Chef's selection of salmon & tuna nigiri and rolls.", "image": u("photo-1579584425555-c3ce17fd4351"), "price": 549, "discount_price": 479, "food_type": "NON_VEG", "rating": 4.6, "preparation_time": "25 min", "is_available": 1, "ingredients": ["sushi rice", "salmon", "tuna", "sesame seeds", "soy sauce", "nori"]},
    {"id": "f15", "restaurant_id": "r5", "cat": "Japanese", "name": "Chicken Ramen", "description": "Rich broth, wheat noodles, soft egg & scallions.", "image": u("photo-1569718212165-3a8278d5f624"), "price": 419, "discount_price": None, "food_type": "NON_VEG", "rating": 4.5, "preparation_time": "25 min", "is_available": 1, "ingredients": ["wheat noodles", "chicken broth", "egg", "soy sauce", "scallion"]},
    {"id": "f16", "restaurant_id": "r6", "cat": "Fast Food", "name": "Classic Chicken Burger", "description": "Crispy chicken patty, cheese, lettuce & house sauce.", "image": u("photo-1568901346375-23c9450c58cd"), "price": 219, "discount_price": 179, "food_type": "NON_VEG", "rating": 4.4, "preparation_time": "20 min", "is_available": 1, "ingredients": ["chicken patty", "wheat bun", "cheese", "lettuce", "sesame seeds"]},
    {"id": "f17", "restaurant_id": "r6", "cat": "Fast Food", "name": "Crispy Veg Burger", "description": "Golden veggie patty with tangy sauce & crunchy slaw.", "image": u("photo-1550547660-d9450f859349"), "price": 149, "discount_price": 129, "food_type": "VEG", "rating": 4.2, "preparation_time": "15 min", "is_available": 1, "ingredients": ["veggie patty", "wheat bun", "cheese", "lettuce"]},
    {"id": "f18", "restaurant_id": "r6", "cat": "Fast Food", "name": "Peri Peri Fries", "description": "Crackly fries dusted with fiery peri peri spice.", "image": u("photo-1573080496219-bb080dd4f877"), "price": 119, "discount_price": 99, "food_type": "VEG", "rating": 4.3, "preparation_time": "15 min", "is_available": 1, "ingredients": ["potato", "oil", "peri peri spice"]},
    {"id": "f19", "restaurant_id": "r7", "cat": "Seafood", "name": "Prawn Ghee Roast", "description": "Juicy prawns tossed in spicy ghee-roasted masala.", "image": u("photo-1565680018434-b513d5e5fd47"), "price": 459, "discount_price": 389, "food_type": "NON_VEG", "rating": 4.7, "preparation_time": "30 min", "is_available": 1, "ingredients": ["prawns", "ghee", "tomato", "onion", "spices"]},
    {"id": "f20", "restaurant_id": "r7", "cat": "Seafood", "name": "Goan Fish Curry", "description": "Fresh fish simmered in tangy coconut-based curry.", "image": u("photo-1559742811-822873691df8"), "price": 389, "discount_price": 329, "food_type": "NON_VEG", "rating": 4.6, "preparation_time": "35 min", "is_available": 1, "ingredients": ["fish", "coconut", "kokum", "spices", "rice"]},
    {"id": "f21", "restaurant_id": "r9", "cat": "Bengali", "name": "Machher Jhol (Bengali Fish Curry)", "description": "Classic Bengali fish curry with potato & mustard notes.", "image": u("photo-1519708227418-c8fd9a32b7a2"), "price": 369, "discount_price": 319, "food_type": "NON_VEG", "rating": 4.5, "preparation_time": "35 min", "is_available": 1, "ingredients": ["rohu fish", "mustard oil", "potato", "tomato"]},
    {"id": "f22", "restaurant_id": "r8", "cat": "Sweets", "name": "Rasgulla (2 pcs)", "description": "Spongy chenna dumplings soaked in light syrup.", "image": u("photo-1606491956689-2ea866880c84"), "price": 99, "discount_price": 79, "food_type": "VEG", "rating": 4.5, "preparation_time": "10 min", "is_available": 1, "ingredients": ["chenna", "sugar", "cardamom"]},
    {"id": "f23", "restaurant_id": "r10", "cat": "Chinese", "name": "Chilli Chicken", "description": "Crispy chicken tossed with peppers in spicy soy glaze.", "image": u("photo-1603133872878-684f208fb84b"), "price": 279, "discount_price": 239, "food_type": "NON_VEG", "rating": 4.4, "preparation_time": "25 min", "is_available": 1, "ingredients": ["chicken", "soy sauce", "capsicum", "corn starch", "chilli"]},
    {"id": "f24", "restaurant_id": "r10", "cat": "Chinese", "name": "Veg Hakka Noodles", "description": "Wok-tossed noodles with crunchy vegetables.", "image": u("photo-1585032226651-759b368d7246"), "price": 189, "discount_price": 159, "food_type": "VEG", "rating": 4.2, "preparation_time": "20 min", "is_available": 1, "ingredients": ["wheat noodles", "cabbage", "carrot", "soy sauce"]},
    {"id": "f25", "restaurant_id": "r11", "cat": "Kebab", "name": "Mutton Seekh Kebab", "description": "Charcoal-grilled minced mutton skewers with mint.", "image": u("photo-1599487488170-d11ec9c172f0"), "price": 319, "discount_price": 269, "food_type": "NON_VEG", "rating": 4.6, "preparation_time": "25 min", "is_available": 1, "ingredients": ["mutton", "onion", "spices", "mint"]},
    {"id": "f26", "restaurant_id": "r11", "cat": "Kebab", "name": "Paneer Tikka", "description": "Smoky grilled cottage cheese cubes with peppers.", "image": u("photo-1529193591184-b1d58069ecdd"), "price": 259, "discount_price": 219, "food_type": "VEG", "rating": 4.5, "preparation_time": "25 min", "is_available": 1, "ingredients": ["paneer", "yogurt", "spices", "capsicum"]},
    {"id": "f27", "restaurant_id": "r13", "cat": "Spanish", "name": "Spanish Seafood Paella", "description": "Saffron rice with prawns, mussels & olive oil.", "image": u("photo-1534080564583-6be75777b70a"), "price": 629, "discount_price": 549, "food_type": "NON_VEG", "rating": 4.7, "preparation_time": "40 min", "is_available": 1, "ingredients": ["arborio rice", "prawns", "mussels", "saffron", "olive oil"]},
    {"id": "f28", "restaurant_id": "r13", "cat": "Spanish", "name": "Patatas Bravas", "description": "Crispy potato bites with smoky tomato sauce.", "image": u("photo-1512621776951-a57141f2eefd"), "price": 199, "discount_price": None, "food_type": "VEG", "rating": 4.1, "preparation_time": "20 min", "is_available": 0, "ingredients": ["potato", "tomato sauce", "olive oil", "paprika"]},
    {"id": "f29", "restaurant_id": "r8", "cat": "Dessert", "name": "Chocolate Brownie Sundae", "description": "Warm brownie, ice cream, hot fudge & roasted nuts.", "image": u("photo-1563805042-7684c019e1cb"), "price": 239, "discount_price": 199, "food_type": "VEG", "rating": 4.7, "preparation_time": "15 min", "is_available": 1, "ingredients": ["chocolate", "flour", "butter", "egg", "vanilla ice cream", "almonds"]},
    {"id": "f30", "restaurant_id": "r12", "cat": "Chocolate", "name": "Chocolate Truffle Pastry", "description": "Decadent layered pastry with dark chocolate ganache.", "image": u("photo-1578985545062-69928b1d9587"), "price": 189, "discount_price": 149, "food_type": "VEG", "rating": 4.6, "preparation_time": "10 min", "is_available": 1, "ingredients": ["dark chocolate", "cream", "flour", "egg", "butter"]},
    {"id": "f31", "restaurant_id": "r14", "cat": "Donuts", "name": "Assorted Glazed Donuts (6 pcs)", "description": "Box of six freshly glazed assorted donuts.", "image": u("photo-1551024601-bec78aea704b"), "price": 249, "discount_price": 199, "food_type": "VEG", "rating": 4.5, "preparation_time": "15 min", "is_available": 1, "ingredients": ["flour", "sugar", "milk", "egg", "butter", "chocolate glaze"]},
    {"id": "f32", "restaurant_id": "r14", "cat": "Donuts", "name": "Chocolate Fudge Donut", "description": "Soft donut drenched in rich chocolate fudge.", "image": u("photo-1551024506-0bccd828d307"), "price": 99, "discount_price": 79, "food_type": "VEG", "rating": 4.4, "preparation_time": "10 min", "is_available": 1, "ingredients": ["flour", "chocolate", "milk", "egg", "sugar"]},
    {"id": "f33", "restaurant_id": "r7", "cat": "Drinks", "name": "Fresh Lime Soda", "description": "Zesty lime with fizzy soda — sweet, salted or mixed.", "image": u("photo-1513558161293-cdaf765ed2fd"), "price": 89, "discount_price": 69, "food_type": "VEG", "rating": 4.2, "preparation_time": "10 min", "is_available": 1, "ingredients": ["lime", "soda", "sugar", "mint"]},
    {"id": "f34", "restaurant_id": "r15", "cat": "North Indian", "name": "Amritsari Chole Kulche", "description": "Buttery kulche with spicy chickpea curry.", "image": u("photo-1601050690597-df0568f70950"), "price": 199, "discount_price": 169, "food_type": "VEG", "rating": 4.6, "preparation_time": "25 min", "is_available": 1, "ingredients": ["wheat flour", "chickpeas", "butter", "onion", "spices"]},
    {"id": "f35", "restaurant_id": "r15", "cat": "North Indian", "name": "Tandoori Chicken", "description": "Yogurt-spice marinated chicken grilled in the tandoor.", "image": u("photo-1544025162-d76694265947"), "price": 339, "discount_price": 289, "food_type": "NON_VEG", "rating": 4.5, "preparation_time": "30 min", "is_available": 1, "ingredients": ["chicken", "yogurt", "spices", "lemon"]}
]

COUPONS = [
    {"code": "WELCOME50", "discount_type": "PERCENT", "discount_value": 50, "min_subtotal": 199, "max_discount": 100, "is_active": 1},
    {"code": "FOODY100", "discount_type": "FLAT", "discount_value": 100, "min_subtotal": 399, "max_discount": 100, "is_active": 1},
    {"code": "FREEDEL", "discount_type": "FLAT", "discount_value": 40, "min_subtotal": 149, "max_discount": 40, "is_active": 1},
    {"code": "PARTY200", "discount_type": "FLAT", "discount_value": 200, "min_subtotal": 799, "max_discount": 200, "is_active": 1}
]

DEMO_USER = {
    "id": "u_demo_1",
    "name": "Aarav Sharma",
    "email": "demo@foody.in",
    "phone": "9876543210",
    "password": "foody123",
    "avatar": "fa-user",
    "role": "user"
}

ADMIN_USER = {
    "id": "u_admin_karan",
    "name": "Karan",
    "email": "karan@foody.in",
    "phone": "9876543211",
    "password": "karan123",
    "avatar": "fa-user-shield",
    "role": "admin",
    "is_super_admin": 1
}

NITIN_ADMIN_USER = {
    "id": "u_admin_nitin",
    "name": "Nitin",
    "email": "nitin@foody.in",
    "phone": "9876543212",
    "password": "nitin123",
    "avatar": "fa-user-shield",
    "role": "admin",
    "is_super_admin": 1
}
